# Generated by Django 5.1.1 on 2024-09-18 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('costureira', models.CharField(choices=[('Maria', 'MARIA'), ('Julia', 'JULIA'), ('Carlinha', 'CARLINHA')], max_length=10)),
                ('descricao', models.TextField(max_length=160)),
                ('data_pedido', models.DateTimeField()),
                ('data_entrega', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
