# Generated by Django 5.1.1 on 2024-09-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servicos'),
        ),
    ]
