# Generated by Django 5.1.1 on 2024-10-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Em Andamento'), (1, 'Concluido'), (2, 'Entregue')], default=0),
        ),
    ]
