# Generated by Django 5.1.1 on 2025-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_alter_ordem_data_entrega_alter_ordem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemitem',
            name='comissao',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
