# Generated by Django 5.1.1 on 2025-01-14 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_ordemitem_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemitem',
            name='comissao',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
