# Generated by Django 5.1.1 on 2025-01-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_alter_ordemitem_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemitem',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
