# Generated by Django 5.1.1 on 2025-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_ordemitem_preco_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemitem',
            name='valor_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
