# Generated by Django 5.1.1 on 2024-10-19 20:12

import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
