# Generated by Django 5.1.1 on 2025-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costureiras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costureira',
            name='comissao',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costureira',
            name='cpf',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
