# Generated by Django 5.1.1 on 2025-01-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costureiras', '0002_costureira_comissao_costureira_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costureira',
            name='comissao',
        ),
    ]
